###
POST http://localhost:4000/registro HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taco100",
    "apellidoPaterno": "Machuca",
	"apellidoMaterno": "Da la teja",
	"correoElectronico": "mikehotpussy@oio.poio",
	"nombreUsuario": "xxChicoBuapo_PussyDestroyer1xx",
	"contrasena": "1234",
    "reputacion": 2
}

###
GET http://localhost:4000/registro HTTP/1.1

###
GET http://localhost:4000/registro/60f5dc90f598fe1ea867eee9 HTTP/1.1

###
PUT http://localhost:4000/registro/60f5dc90f598fe1ea867eee9 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taco3",
    "apellidoPaterno": "Antonio",
	"apellidoMaterno": "Da la teja",
	"correoElectronico": "mikehotpussy@oio.poiote",
	"nombreUsuario": "xxChicoPrieto(no-por-eso-menos-guapo-pero-si-con-menos-derechos-,-ninguno)_PussyDestroyer2xx",
	"contrasena": "1234",
    "reputacion": 2
}

###
DELETE http://localhost:4000/registro/60f5dc6ef598fe1ea867eee6 HTTP/1.1




//----------------------- USUARIO RESPONSABLE
###
GET http://localhost:4000/registro-responsable HTTP/1.1


###
POST http://localhost:4000/registro-responsable HTTP/1.1
Content-Type: application/json

{
    "institucion": "SIAPA",
    "nombreUsuario": "responsable2",
	"contrasena": "responsable2",
	"reporteAsignado": {
            "folio": "s00002",
            "tipoProblema": "Falta de alcantarilla",
            "urgencia": 85,
            "fechaCreacion": "2021-01-20",
            "estado": "En proceso",
            "ubicacion": {
                "longitud": 201.145132,
                "latitud": 20.5430167
            }
        }
}

###
GET http://localhost:4000/registro-responsable/60fa2b8e338b1627308b9b12 HTTP/1.1

###
PUT http://localhost:4000/registro-responsable/60fa2b8e338b1627308b9b12 HTTP/1.1
Content-Type: application/json

{
    "institucion": "Infrestructura",
    "nombreUsuario": "responsable1",
	"contrasena": "responsable1",
	"reporteAsignado": {
            "folio": "i0002",
            "tipoProblema": "Socavon",
            "urgencia": 85,
            "fechaCreacion": "2021-01-20",
            "estado": "Desatendido",
            "ubicacion": {
                "longitud": 201.145132,
                "latitud": 20.5430167
            }
        }
}

###
DELETE http://localhost:4000/registro-responsable/60fa2b8e338b1627308b9b12 HTTP/1.1