###
POST http://localhost:4000/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taco2",
    "apellidoPaterno": "Machuca",
	"apellidoMaterno": "Da la teja",
	"correoElectronico": "mikehotpussy@oio.poio",
	"nombreUsuario": "xxChicoBuapo_PussyDestroyer1xx",
	"contrasena": "1234",
    "reputacion": 2
}

###
GET http://localhost:4000/usuarios HTTP/1.1

###
GET http://localhost:4000/usuarios/60f5dc90f598fe1ea867eee9 HTTP/1.1

###
PUT http://localhost:4000/usuarios/60f5dc90f598fe1ea867eee9 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taco3",
    "apellidoPaterno": "Antonio",
	"apellidoMaterno": "Da la teja",
	"correoElectronico": "mikehotpussy@oio.poiote",
	"nombreUsuario": "xxChicoPrieto(no-por-eso-menos-guapo-pero-si-con-menos-derechos-,-ninguno)_PussyDestroyer2xx",
	"contrasena": "1234",
    "reputacion": 2
}

###
DELETE http://localhost:4000/usuarios/60f5dc6ef598fe1ea867eee6 HTTP/1.1